---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: npm
    directory: "/javascript"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "lodash"
        versions: ["4.17.x"]
  - package-ecosystem: bundler
    directory: "/ruby"
    schedule:
      interval: "weekly"
